[build]
command = "npx next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
included_files = ["lib/**"]

[[edge_functions]]
function = "send-reminders-cron"
path = "/api/cron/trigger-reminders"
